# Generated by Django 5.2.5 on 2025-09-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0004_remove_products_color_products_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='color',
            new_name='colors',
        ),
    ]
