# Generated by Django 5.2.5 on 2025-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cancel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
