# Generated by Django 5.2.5 on 2025-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0008_products_cancel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
