# Generated by Django 5.2.5 on 2025-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0009_products_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('coupon_amount', models.IntegerField()),
            ],
        ),
    ]
