# Generated by Django 5.2.5 on 2025-09-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0010_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footwear.user'),
        ),
    ]
