# Generated by Django 5.2.5 on 2025-09-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0011_coupons_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='uid',
        ),
        migrations.CreateModel(
            name='Applied_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_coupon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear.coupons')),
                ('applied_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear.user')),
            ],
        ),
    ]
