# Generated by Django 5.2.5 on 2025-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0012_remove_coupons_uid_applied_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
