# Generated by Django 5.2.5 on 2025-09-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0014_alter_coupons_valid_from_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='minimum_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
