# Generated by Django 5.2.5 on 2025-09-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0015_coupons_minimum_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
