# Generated by Django 5.2.5 on 2025-09-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0016_cart_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footwear.coupons'),
        ),
    ]
