# Generated by Django 5.2.5 on 2025-09-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0017_alter_cart_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
