# Generated by Django 5.2.5 on 2025-09-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0018_alter_cart_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_code',
        ),
    ]
