# Generated by Django 5.2.5 on 2025-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0019_remove_cart_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='already_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
