# Generated by Django 5.2.5 on 2025-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0020_coupons_already_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
