# Generated by Django 5.2.5 on 2025-09-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0021_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
