# Generated by Django 5.2.5 on 2025-09-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0022_remove_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='already_claimed',
        ),
    ]
