# Generated by Django 5.2.5 on 2025-09-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0024_adresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('final_amount', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear.adresses')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear.user')),
            ],
        ),
    ]
