# Generated by Django 5.2.5 on 2025-09-25 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0030_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
