# Generated by Django 5.2.5 on 2025-09-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0032_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='footwear.products'),
        ),
    ]
